// Generated by https://quicktype.io

export interface IResProducto {
    total: number;
    datos: Dato[];
}

export interface Dato {
    _id:    string;
    Nombre: string;
    Estado: boolean;
    Precio: number;
    Costo:  number;
    Minimo: number;
    Stock:  number;
    __v:    number;
}
